In [4]:
import numpy as np
import pandas as pd

dfl = pd.read_csv('listings.csv')
dfc = pd.read_csv('calendar.csv')
dfr = pd.read_csv('reviews.csv')
pd.set_option('display.max_columns', None)

/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3251: DtypeWarning: Columns (67) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
dfl.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,https://www.airbnb.com/rooms/2595,20220106025017,2022-01-06,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,"New York, New York, United States",A New Yorker since 2000! My passion is creatin...,within a day,51%,17%,f,https://a0.muscache.com/im/pictures/user/50fc5...,https://a0.muscache.com/im/pictures/user/50fc5...,Midtown,8.0,8.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"New York, United States",Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,NaN,1 bath,NaN,1.0,"[""Hot water"", ""Iron"", ""Keypad"", ""Refrigerator""...",$150.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,30,60,90,334,2022-01-06,48,0,0,2009-11-21,2019-11-04,4.70,4.72,4.62,4.76,4.79,4.86,4.41,NaN,f,3,3,0,0,0.33
1,3831,https://www.airbnb.com/rooms/3831,20220106025017,2022-01-06,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,https://a0.muscache.com/pictures/e49999c2-9fd5...,4869,https://www.airbnb.com/users/show/4869,LisaRoxanne,2008-12-07,"New York, New York, United States",Laid-back Native New Yorker (formerly bi-coast...,a few days or more,0%,64%,f,https://a0.muscache.com/im/users/4869/profile_...,https://a0.muscache.com/im/users/4869/profile_...,Clinton Hill,1.0,1.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"Brooklyn, New York, United States",Bedford-Stuyvesant,Brooklyn,40.68494,-73.95765,Entire guest suite,Entire home/apt,3,NaN,1 bath,1.0,3.0,"[""Hot water"", ""Iron"", ""Children\u2019s books a...",$73.00,1,730,1.0,1.0,730.0,730.0,1.0,730.0,NaN,t,3,15,26,214,2022-01-06,409,26,0,2014-09-30,2021-10-22,4.45,4.58,4.49,4.78,4.80,4.71,4.64,NaN,f,1,1,0,0,4.62
2,5121,https://www.airbnb.com/rooms/5121,20220106025017,2022-01-06,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,Garon,2009-02-03,"New York, New York, United States","I am an artist(painter, filmmaker) and curato...",within an hour,100%,100%,f,https://a0.muscache.com/im/pictures/user/72a61...,https://a0.muscache.com/im/pictures/user/72a61...,Bedford-Stuyvesant,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,NaN,NaN,1.0,1.0,"[""Heating"", ""Air conditioning"", ""Long term sta...",$60.00,30,730,30.0,30.0,730.0,730.0,30.0,730.0,NaN,t,30,60,90,365,2022-01-06,50,0,0,2009-05-28,2019-12-02,4.52,4.22,4.09,4.91,4.91,4.47,4.52,NaN,f,2,0,2,0,0.33
3,5136,https://www.airbnb.com/rooms/5136,20220106025017,2022-01-06,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,Rebecca,2009-02-03,"Brooklyn, New York, United States","Rebecca is an artist/designer, and Henoch is i...",NaN,NaN,25%,f,https://a0.muscache.com/im/users/7378/profile_...,https://a0.muscache.com/im/users/7378/profile_...,Greenwood Heights,1.0,1.0,"['email', 'phone', 'reviews']",t,t,NaN,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,NaN,1.5 baths,2.0,2.0,"[""Cable TV"", ""TV with standard cable"", ""Outdoo...",$275.00,5,1125,5.0,5.0,1125.0,1125.0,5.0,1125.0,NaN,t,0,9,9,152,2022-01-06,2,1,0,2014-01-02,2021-08-08,5.00,5.00,5.00,5.00,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
4,5178,https://www.airbnb.com/rooms/5178,20220106025017,2022-01-07,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,Shunichi,2009-03-03,"New York, New York, United States",I used to work for a financial industry but no...,within a few hours,100%,100%,f,https://a0.muscache.com/im/users/8967/profile_...,https://a0.muscache.com/im/users/8967/profile_...,Hell's Kitchen,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,"New York, United States",Midtown,Manhattan,40.76457,-73.98317,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Hot water"", ""Body soap"", ""Iron"", ""Lock on be...",$68.00,2,14,2.0,2.0,14.0,14.0,2.0,14.0,NaN,t,9,24,34,198,2022-01-07,514,40,4,2009-05-06,2021-12-21,4.22,4.21,3.73,4.66,4.42,4.87,4.36,NaN,f,1,0,1,0,3.33

In [3]:
dfl.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [6]:
dfl.shape

(38185, 74)

In [10]:
dfl.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.818500e+04,3.818500e+04,3.818500e+04,38138.000000,38138.000000,38185.000000,38185.000000,38185.000000,0.0,34296.000000,36898.000000,38185.000000,3.818500e+04,38167.000000,38167.000000,3.816700e+04,3.816700e+04,38167.000000,3.816700e+04,0.0,38185.000000,38185.000000,38185.000000,38185.000000,38185.000000,38185.000000,38185.000000,29009.000000,28426.000000,28437.000000,28420.000000,28430.000000,28417.000000,28416.000000,38185.000000,38185.000000,38185.000000,38185.000000,29009.000000
mean,3.023392e+07,2.022011e+13,1.179367e+08,51.292490,51.292490,40.729029,-73.948213,2.793846,NaN,1.323274,1.587024,21.165903,5.792662e+04,21.496895,27.280399,1.352214e+06,3.546574e+06,26.884219,2.493696e+06,NaN,10.927851,24.310672,38.269320,139.818672,23.800000,5.559958,0.618437,4.593195,4.746083,4.616173,4.813633,4.807735,4.747747,4.647671,17.788320,8.099385,9.574414,0.052481,1.100220
std,1.764823e+07,0.000000e+00,1.322215e+08,322.326139,322.326139,0.055880,0.051343,1.870907,NaN,0.703207,1.075630,29.024816,1.099058e+07,34.719683,70.383118,5.383463e+07,8.717728e+07,68.610076,7.026044e+07,NaN,12.720317,25.601879,38.451678,145.357261,51.065326,15.239171,1.534544,0.816873,0.486332,0.569287,0.434866,0.458277,0.417150,0.513094,58.000421,35.971495,41.910666,0.471057,1.772447
min,2.595000e+03,2.022011e+13,2.438000e+03,0.000000,0.000000,40.504560,-74.249840,0.000000,NaN,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,1.365653e+07,2.022011e+13,1.167544e+07,1.000000,1.000000,40.688930,-73.983120,2.000000,NaN,1.000000,1.000000,3.000000,6.000000e+01,2.000000,3.000000,3.600000e+02,3.650000e+02,3.000000,3.650000e+02,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,4.570000,4.700000,4.500000,4.800000,4.810000,4.670000,4.550000,1.000000,0.000000,0.000000,0.000000,0.120000
50%,3.183416e+07,2.022011e+13,5.150184e+07,1.000000,1.000000,40.724800,-73.954360,2.000000,NaN,1.000000,1.000000,30.000000,1.124000e+03,30.000000,30.000000,1.125000e+03,1.125000e+03,30.000000,1.125000e+03,NaN,2.000000,12.000000,29.000000,87.000000,4.000000,0.000000,0.000000,4.820000,4.900000,4.800000,4.960000,4.970000,4.870000,4.780000,1.000000,1.000000,0.000000,0.000000,0.440000
75%,4.733424e+07,2.022011e+13,2.047046e+08,3.000000,3.000000,40.762530,-73.929550,4.000000,NaN,1.000000,2.000000,30.000000,1.125000e+03,30.000000,30.000000,1.125000e+03,1.125000e+03,30.000000,1.125000e+03,NaN,26.000000,54.000000,83.000000,304.000000,21.000000,4.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,1.000000,2.000000,0.000000,1.530000
max,5.416164e+07,2.022011e+13,4.387934e+08,3750.000000,3750.000000,40.914350,-73.710870,16.000000,NaN,13.000000,24.000000,1250.000000,2.147484e+09,1250.000000,1250.000000,2.147484e+09,2.147484e+09,1250.000000,2.147484e+09,NaN,30.000000,60.000000,90.000000,365.000000,1010.000000,713.000000,80.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,399.000000,314.000000,343.000000,10.000000,92.920000

In [21]:
dfl.iloc[8416:8420]

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
8416,11928097,https://www.airbnb.com/rooms/11928097,20220106025017,2022-01-06,Sunny room in a 2 bedroom apartment,My room is sunny and comfortable with a new qu...,NaN,https://a0.muscache.com/pictures/7be913f2-cb31...,17737517,https://www.airbnb.com/users/show/17737517,Martin,2014-07-06,"New York, New York, United States",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/48733...,https://a0.muscache.com/im/pictures/user/48733...,East Harlem,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,NaN,East Harlem,Manhattan,40.80012,-73.94272,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Smoke alarm"", ""Elevator"", ""Essentials"", ""Han...",$65.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,f,0,0,0,0,2022-01-06,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
8417,11929230,https://www.airbnb.com/rooms/11929230,20220106025017,2022-01-06,Spacious Room in Williamsburg,"Hey,<br /><br />Cozy and spacious private bedr...",NaN,https://a0.muscache.com/pictures/9489dbb0-67af...,31919152,https://www.airbnb.com/users/show/31919152,Ryan,2015-04-25,"Salt Lake City, Utah, United States",Photographer + Director + Trucker\rSLC,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/19857...,https://a0.muscache.com/im/pictures/user/19857...,Williamsburg,1.0,1.0,"['email', 'phone', 'facebook', 'jumio', 'offli...",t,t,NaN,Williamsburg,Brooklyn,40.70878,-73.94441,Private room in rental unit,Private room,1,NaN,1 bath,1.0,1.0,"[""Lock on bedroom door"", ""Smoke alarm"", ""Long ...",$60.00,7,1125,7.0,7.0,1125.0,1125.0,7.0,1125.0,NaN,f,0,0,0,0,2022-01-06,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
8418,11935301,https://www.airbnb.com/rooms/11935301,20220106025017,2022-01-06,"Spacious, Sunny Room in Park Slope","Spacious, sunny room in owner occupied house i...",NaN,https://a0.muscache.com/pictures/87660836/53bc...,24253453,https://www.airbnb.com/users/show/24253453,Lisah,2014-11-28,"New York, New York, United States",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/users/24253453/prof...,https://a0.muscache.com/im/users/24253453/prof...,Park Slope,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'kba', ...",t,t,NaN,Park Slope,Brooklyn,40.67606,-73.98116,Private room in residential home,Private room,2,NaN,1.5 baths,1.0,1.0,"[""Fire extinguisher"", ""Iron"", ""Lock on bedroom...",$85.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,0,0,1,2022-01-06,1,0,0,2016-06-24,2016-06-24,5.0,5.0,5.00,5.0,5.00,5.00,5.00,NaN,f,1,0,1,0,0.01
8419,11937647,https://www.airbnb.com/rooms/11937647,20220106025017,2022-01-06,Entire Williamsburg apt.,– In the heart of trendy Williamsburg NYC. <br...,Located a few meters from L subway which bring...,https://a0.muscache.com/pictures/896df596-2e63...,12446288,https://www.airbnb.com/users/show/12446288,Micki & Kristian,2015-12-11,"New York, New York, United States",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/a5620...,https://a0.muscache.com/im/pictures/user/a5620...,Williamsburg,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Brooklyn, New York, United States",Williamsburg,Brooklyn,40.71508,-73.93768,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,1.0,"[""Smoke alarm"", ""Air conditioning"", ""Essential...",$90.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,0,0,0,2022-01-06,4,0,0,2016-03-31,2018-05-30,4.5,5.0,4.75,4.0,4.25,4.75,4.25,NaN,f,1,1,0,0,0.06

In [7]:
dfc.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2595,2022-01-06,t,$150.00,$150.00,30.0,1125.0
1,3831,2022-01-06,f,$73.00,$73.00,1.0,730.0
2,3831,2022-01-07,f,$73.00,$73.00,1.0,730.0
3,3831,2022-01-08,f,$73.00,$73.00,1.0,730.0
4,3831,2022-01-09,f,$73.00,$73.00,1.0,730.0

In [8]:
dfc.shape

(13930969, 7)

In [9]:
dfc.describe()

         listing_id  minimum_nights  maximum_nights
count  1.393097e+07    1.393095e+07    1.393095e+07
mean   3.022667e+07    2.688357e+01    2.501114e+06
std    1.764893e+07    6.931499e+01    7.321817e+07
min    2.595000e+03    1.000000e+00    1.000000e+00
25%    1.365323e+07    3.000000e+00    3.650000e+02
50%    3.180971e+07    3.000000e+01    1.125000e+03
75%    4.733426e+07    3.000000e+01    1.125000e+03
max    5.416164e+07    1.250000e+03    2.147484e+09

In [11]:
dfr.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2595,17857,2009-11-21,50679,Jean,Notre séjour de trois nuits.\r<br/>Nous avons ...
1,2595,19176,2009-12-05,53267,Cate,Great experience.
2,2595,19760,2009-12-10,38960,Anita,I've stayed with my friend at the Midtown Cast...
3,2595,34320,2010-04-09,71130,Kai-Uwe,"We've been staying here for about 9 nights, en..."
4,2595,46312,2010-05-25,117113,Alicia,We had a wonderful stay at Jennifer's charming...

In [12]:
dfr.shape

(908803, 6)